language: rust
rust:
  - nightly
      env: FEATURES=''
  - stable
      env: FEATURES=''
  # The following Rust version represents the oldest supported version of brotli
  - 1.6.0
      env: FEATURES=disable-timer

os:
  - linux
  - osx

script:
  - cargo test --features="$FEATURES"
