[package]
name = "brotli"
version = "0.0.1"
authors = ["Daniel Reiter Horn <danielrh@dropbox.com>"]
license = "MIT license"
repository = "https://github.com/dropbox/rust-brotli"

[[bin]]
doc = false
name = "brot"

[dependencies]
"alloc-no-stdlib" = { git = "https://github.com/dropbox/rust-alloc-no-stdlib.git"}
"brotli-no-stdlib" = { git = "https://github.com/dropbox/rust-brotli-no-stdlib.git"}
