[package]
name = "brotli-no-stdlib"
version = "0.0.1"
authors = ["Daniel Reiter Horn <danielrh@dropbox.com>"]
license = "MIT license"
repository = "https://github.com/dropbox/rust-brotli-no-stdlib"

[[bin]]
doc = false
name = "brot"

[dependencies]
"alloc-no-stdlib" = {rev="a0ce52bc6ae8878103871794a356cdb194042224", git = "https://github.com/dropbox/rust-alloc-no-stdlib.git"}
